#!/bin/bash

# mReschke dbox (docker dev box) command helper
# mReschke 2015-01-12

# Data Container
function data_init {
	echo "Initialize shared data docker container"
	docker run --name dbox-data -v ~/.dbox:/data:rw mreschke/data
}

# MySQL Container
function mysql_init {
	echo "Initialize mysql docker container"
	docker run -d --name mysql -p 3306:3306 --volumes-from dbox-data mreschke/mariadb
}
function mysql_console {
	#docker run -it --rm --link mysql:mysql mreschke/mariadb bash -c 'mysql -h $MYSQL_PORT_3306_TCP_ADDR'
	docker exec -it mysql mysql -uroot -p
}

# Redis Container
function redis_init {
	echo "Initialize redis docker container"
	docker run -d --name redis -p 6379:6379 --volumes-from dbox-data mreschke/redis
}
function redis_console {
	#docker run -it --rm --link redis:redis mreschke/redis bash -c 'redis-cli -h "$REDIS_PORT_6379_TCP_ADDR" -p "$REDIS_PORT_6379_TCP_PORT"'
	docker exec -it redis redis-cli
}

# PHP Container
function php_init {
	echo "Initialize php docker container"
	docker run -d --name php mreschke/phpfpm
}

# Web Container
function web_init {
	echo "Initialize web docker container"
	docker run -d --name web -p 80:80 -p 443:443 --link mysql:mysql --link redis:redis --link php:php --volumes-from dbox-data mreschke/nginx
}


# Common Functions
function up {
	echo "Starting $1 docker container"
	docker start $1
}
function down {
	echo "Stopping $1 docker container"
	docker stop $1
}
function destroy {
	echo "Destroying $1 docker container"
	docker stop $1
	docker rm $1
}
function shell {
	docker exec -it $1 bash
}

# Initialize dbox (first time use)
function init {
	# Initialize dbox if not already done
	echo "Initializing first time dbox environment"

	if [ ! -d ~/.dbox ]; then
		echo "Init ~/.dbox"
		git clone https://github.com/mreschke/dbox ~/.dbox
		ln -sf ~/.dbox/dbox /usr/local/bin/
	fi

	echo "Init all containers"
	data_init
	mysql_init
	redis_init
	php_init
	web_init

	echo "Initialization complete!"
	echo
}

function usage {
	echo "dbox (Docker PHP dev box) 1.0"
	echo "Copyright (C) 2015 Matthew Reschke"
	echo "License MIT <mreschke.com/license/mit>"
	echo "Written by Matthew Reschke <mail@mreschke.com> on 2015-01-12"
	echo
	echo "Usage:"
	echo "  dbox up            bring up all containers (entire dev environment)"
}


if [ "$2" == "" ]; then
	cmd=$1
	if [ "$cmd" == "up" ]; then
		up mysql
		up redis
		up php
		up web

	elif [ "$cmd" == "down" ]; then
		down web
		down php
		down redis
		down mysql

	elif [ "$cmd" == "init" ]; then
		init

	elif [ "$cmd" == "destroy" ]; then
		echo "Destroying all containers, your data is safe at ~/.dbox"
		down web ; docker rm web
		down php ; docker rm php
		down redis ; docker rm redis
		down mysql ; docker rm mysql
		docker rm dbox-data
	
	elif [ "$cmd" == "pull" ]; then
		docker pull mreschke/jessie-base
		docker pull mreschke/mariadb
		docker pull mreschke/redis
		docker pull mreschke/phpfpm
		docker pull mreschke/nginx

	else
		usage
	fi
else
	container=$1
	cmd=$2

	if [ "$cmd" == "shell" ]; then
		shell $container
	elif [ "$cmd" == "up" ]; then
		up $container
	elif [ "$cmd" == "down" ]; then
		down $container
	elif [ "$cmd" == "destroy" ]; then
		destroy $container
	else
		${container}_${cmd}
	fi
fi

